# The Site Configuration

theme: jekyll-theme-chirpy
baseurl: ""  # GitHub Pages root path
url: "https://youkamii.github.io"

lang: ko
timezone: Asia/Seoul

title: Youkamii
tagline: Jeong's Blog
description: >-
  Development Articles

# GitHub Metadata
github:
  username: Youkamii

social:
  name: Youkam_Jeong
  email: gkfkd747@naver.com
  links:
    - https://github.com/Youkamii

# SEO
jekyll-seo-tag: true

# Web Analytics
analytics:
  google:
    id: # Add your Google Analytics ID here

# Comments
comments:
  provider: # Leave empty to disable comments

# PWA (Progressive Web App)
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
      - "/example"

paginate: 10

# Syntax Highlighting
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Collections
collections:
  tabs:
    output: true
    sort_by: order

# Default Front Matter
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# Exclusions
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
